# Generated by Django 5.0.1 on 2024-01-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(max_length=100)),
                ('max_value', models.IntegerField(max_length=100)),
                ('rows', models.IntegerField(max_length=2000)),
                ('columns', models.IntegerField(max_length=10)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
